[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
hook_source = '''
let b:clang2_orig_maps = {}
'''
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'

[[plugins]]
repo = 'mitsuse/autocomplete-swift'
on_ft = 'swift'

# [[plugins]]
# repo = 'landaire/deoplete-swift'
# on_ft = 'swift'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_ignore_case = 1
    let g:deoplete#enable_smart_case = 1

    let g:deoplete#sources#swift#daemon_autostart = 1

    " <TAB>: completion.
    imap <silent><expr><TAB> pumvisible() ? "\<C-n>" : <SID>check_back_space() ? "\<TAB>" : deoplete#mappings#manual_complete()
    function! s:check_back_space() abort
        let col = col('.') - 1
        return !col || getline('.')[col - 1]  =~ '\s'
    endfunction

    " <S-TAB>: completion back.
    inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"
'''

